"""empty message

Revision ID: 076e7025886d
Revises: d41f6c73c35b
Create Date: 2023-07-09 02:04:45.533558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076e7025886d'
down_revision = 'd41f6c73c35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
